---
- hosts: all
  become: true
  #vars:
    #users: [client1, client2, client3]
  tasks:
  - name: "Add User"
    user:
      name: client1
      password: client1
      state: present
      file:
        path: "/home/client1/public_html"
        state: directory
  roles:
    - makarenalabs.wordpress
...