---
- name: Installation complete
  hosts: all
  become: true
  vars:
    users: [client1, client2, client3]
  tasks:
    - name: "Add user"
      user:
        name: "{{ item }}"
      file:
        path: /home/"{{ item }}"/public_html
        state: directory
      with_items: "{{ users }}"
    #remote_user: root
    #vars:
    #  user: itesciadmin
    roles:
    - geerlingguy.apache

